Repository Sonichigo/HACKTOBERFEST_2021, pull requests merged in 2020-10, with the labels that each got.

#4 added code for a fractal
  CONTRIBUTORS.md
  Codes/fractal.py
Labels: hacktoberfest-accepted

#5 Added the solution for the amicable sum problem
  CONTRIBUTORS.md
  Codes/amicable_numbers.py
Labels: hacktoberfest-accepted

#2 Add Dancebot
  CONTRIBUTORS.md
  Projects/Dancebot.py
Labels: hacktoberfest-accepted

#1 Add code snippet
  Codes/SQLAlchemy_FastestBulkInsert.py
Labels: hacktoberfest-accepted

#7 diamond pattern
  CONTRIBUTORS.md
  Codes/diamondPattern.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#8 Chat_system_for_multi_user
  Codes/Chat_system_in_cpp/TCP_client
  Codes/Chat_system_in_cpp/TCP_client.c
  Codes/Chat_system_in_cpp/server_file/a.out
  Codes/Chat_system_in_cpp/server_file/server
  Codes/Chat_system_in_cpp/server_file/server.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#9 Add files via upload
  Ananya Singh's Blogging Platform.html
Labels: hacktoberfest, hacktoberfest-accepted

#10 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest, hacktoberfest-accepted

#11 Bubble Sort
  Codes/bs.py
  demo_create_mongo_db.js
Labels: hacktoberfest, hacktoberfest-accepted

#15 New project-Keylogger
  CONTRIBUTORS.md
  Projects/Keylogger/__init__.py
  Projects/Keylogger/key.py
  Projects/Keylogger/keylog.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 personal assistant using python
  personal assistant/BAYMAX.py
  personal assistant/README.md
  personal assistant/requirements.txt
  personal assistant/test.py
Labels: hacktoberfest, hacktoberfest-accepted

#16 LCM finding file
  Codes/LCM.py
Labels: hacktoberfest, hacktoberfest-accepted

#17 new project personal assistant
  Projects/Personal_assistant/__init__.py
  Projects/Personal_assistant/haydel_assistant.py
Labels: hacktoberfest, hacktoberfest-accepted

#18 added a script in code
  CONTRIBUTORS.md
  Codes/n_input_single_line.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#19 Added dart code file and added details in contribution.md file
  CONTRIBUTORS.md
  Codes/area.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#23 Added a python program to check vowels.
  CONTRIBUTORS.md
  Codes/CheckVowel.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#22 Added codes
  CONTRIBUTORS.md
  Codes/Learning-numpy/Learning-numpy-main/LICENSE
  Codes/Learning-numpy/Learning-numpy-main/README.md
  Codes/Learning-numpy/Learning-numpy-main/numpy/Numpy.ipynb
  Codes/Learning-numpy/Learning-numpy-main/numpy/my.png
  Codes/scipy/Scipy.ipynb
  Projects/audiobook/How to Win Every Argument.pdf
  Projects/audiobook/Pdf2Speach.py
  Projects/audiobook/pdf-pg-count.py
  Projects/audiobook/pdf2speachpg.py
  Projects/audiobook/text2speach.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#21 Created password_generator.py
  Projects/password_generator.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#20 Created rock_paper_scissors.py
  Projects/RPS.py
  Projects/rock_paper_scissors.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#24 Added ResverseString.py
  Codes/ReverseString.py
Labels: hacktoberfest, hacktoberfest-accepted
